### ISSUE TITLE
The app deletes my replays for no reason.

### ISSUE THREAD

**Issue by Pyrodragnix** [hotsapi/Hotsapi.Uploader#67]
Every time The app upload the replays, it deletes the replays for no reason. I even tried to reinstall it and still have the same issue. I really don't any coding so any fix to this? ( This is the log said:
[Debug: File (Files location)
[Debug: uploaded File (file Location)
[Info: Deleting replay (file location)

**Comment by martijnhoekstra** [comment]
Thanks for re-reporting.

I strongly suspect that the app deletes your issues with a reason -- at least, I don't think it's possible for the app to delete your replays without one -- so let's try to figure out what the reason is, and how we can fix it. 

Could you first check whether you have any game types to delete selected in the settings window (button "settings" bottom right)?

Please let us know if that is the issue or not (and whether unchecking them fixes the issue).

**Comment by Pyrodragnix** [comment]
oh then nvm. I didn't know that a thing.

**Comment by martijnhoekstra** [comment]
Thanks for checking!
